// Generated by CoffeeScript 1.4.0
(function() {
  var Game, window;

  window = this;

  this.Game = Game = (function() {

    function Game() {}

    Game.prototype.start = function() {
      var c, p;
      p = new Pendulum(100, new Point(100, 100));
      c = new Canvas(window.document.getElementById('canvas'));
      return p.draw(c);
    };

    return Game;

  })();

}).call(this);
